import Banner from "@/components/Banner/Banner";
import ShopCard from "@/components/ShopCard/ShopCard";
import ForYouSection from "@/sections/ForYou/ForYou";
import Hero from "@/sections/Hero/Hero";
import NewEditions from "@/sections/NewEditions/NewEditions";
import SecondSlider from "@/sections/SecondSlider/SecondSlider";
import { MoveLeft } from "lucide-react";
import { Metadata } from "next";
import banner from "@/assets/banner.png"
import banner2 from "@/assets/banner2.png"

export const metadata: Metadata = {
  title: "الفخامة للجلود و الأزياء",
  description: "Generated by create next app",
  icons: "@/assets/logo.svg"
};

export default async function Home() {
  const { data: home_website } = await fetch(`${process.env.NEXT_PUBLIC_API_BASE}/api/client/home_website`).then(res => res.json())
  return (
    <div>
      <Hero slider={home_website?.slider ?? []} />
      <SecondSlider secondSlider={home_website?.main_categories ?? []} />
      <NewEditions products={home_website?.best_seller ?? []} />
      <Banner banner={banner.src} />
      <ForYouSection products={home_website?.for_you ?? []} />
      <Banner banner={banner2.src} />
    </div>
  );
}
