import Banner from "@/components/Banner/Banner";
import ForYouSection from "@/sections/ForYou/ForYou";
import Hero from "@/sections/Hero/Hero";
import NewEditions from "@/sections/NewEditions/NewEditions";
import SecondSlider from "@/sections/SecondSlider/SecondSlider";
import { Metadata } from "next";
import FlashOffers from "@/sections/Flash_offers/FlashOffers";
import Cookies from "js-cookie";
export const metadata: Metadata = {
  title: "الفخامة للجلود و الأزياء",
  description: "Generated by create next app",
  icons: {
    icon: "@/assets/logo.svg"
  }
};

export default async function Home() {
  const token = await Cookies.get("token_luxary")
  const { data: home_website } = await fetch(`${process.env.NEXT_PUBLIC_API_BASE}/api/client/home_website`, {
    headers: { Authorization: `Bearer ${token}` }
  }

  ).then(res => res.json())
  return (
    <div>
      <Hero slider={home_website?.slider ?? []} />
      <SecondSlider secondSlider={home_website?.main_categories ?? []} />
      <NewEditions products={home_website?.best_seller ?? []} />
      <FlashOffers />
      <Banner banner={home_website?.middle_slider ?? ''} />
      <ForYouSection title="اختارنا لك" products={home_website?.for_you ?? []} />
      <Banner banner={home_website?.footer_slider ?? ''} />
    </div>
  );
}
